### ISSUE TITLE
训练集

### ISSUE THREAD

**Issue by woshizhangcheng** [dmuqlzhang/fall_down-detect-yolov4#2]
你好，华录杯训练集已无法下载，不知道up是否有原始数据，能否共享一份

**Comment by dmuqlzhang** [comment]
> 你好，华录杯训练集已无法下载，不知道up是否有原始数据，能否共享一份

你好，华录杯训练数据链接：  https://pan.baidu.com/s/15HCKHvtqnP8TOuNxONNr4Q  提取码：rydd
